app/models.py
from app import db

class Task(db.Model):
    id = db.Column(db.Integer, primary_key = True)
    title = db.Column(db.String(100), nullable = False)
    status = db.Column(db.String(20), default = "Pending")

app/__init__.py
# this file is called App Factory


from flask import Flask
from flask_sqlalchemy import SQLAlchemy

# create databse object globally
db = SQLAlchemy()

def create_app():
    app = Flask(__name__)

    app.config['SECRET_KEY'] = 'MY-SECRET-KEY'
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///todo.db'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

    db.__init__(app) # connecting db

    from app.routes.auth import auth_bp
    from app.routes.tasks import tasks_bp
    app.register_blueprint(auth_bp)
    app.register_blueprint(tasks_bp)

    return app
    

app/routes/auth.py
from flask import Blueprint,render_template,request,redirect,url_for,flash,session

auth_bp = Blueprint('auth',__name__)

# dummy user
USER_CREDENTIAL = {
    'username' : 'admin',
    'password' : '1234'
}

@auth_bp.route('/login', methods=["GET","POST"])
def login():
    if request.method == "POST":
        username = request.form.get('username')
        password = request.form.get('password')

        if username == USER_CREDENTIAL['username'] and password == USER_CREDENTIAL['password']:
            session['user'] = username

            flash("Logged in Successfully", 'success')
        else:
            flash("Inavlid username or password", 'Authentication issue!')
    
    return render_template('login.html')

@auth_bp.route('/logout')
def logout():
    session.pop('user', None)
    flash('Logged out successfully', 'info')
    return redirect(url_for('auth.login'))

app/routes/tasks.py
from flask import Blueprint,render_template,redirect,session,url_for,flash,request
from app import db
from app.models import Task

tasks_bp = Blueprint('tasks', __name__)

@tasks_bp.route('/')
def view_task():
    if 'user' not in session:
        return redirect(url_for('auth.login'))
    
    tasks = Task.query.all()
    return render_template('task.html', tasks = tasks)

@tasks_bp.route('/add', methods=["GET","POST"])
def add_task():
    if 'user' not in session:
        return redirect(url_for('auth.login'))
    
    title = request.form.get('title')
    if title:
        new_task = Task(title=title, status = 'Pending')
        db.session.add(new_task)
        db.session.commit()
        flash("Task added successfully",'success')
    
    return redirect(url_for('tasks.view_task'))

@tasks_bp.route('/toggle/<int:task_id>', methods=["POST"])
def toogle_status(task_id):
    task = Task.query.get(task_id)
    if task:
        if task.status == 'Pending':
            task.status = 'Working'
        elif task.status == 'Working':
            task.status = 'Done'
        else:
            task.status = 'Pending'
        db.session.commit()
    return redirect(url_for('tasks.view_task'))

@tasks_bp.route('/clear',methods=["POST"])
def clear_task():
    Task.query.delete()
    db.session.commit()
    flash("All task cleared", 'info')
    return redirect(url_for('tasks.view_task'))

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {%block title%} To Do App {%endblock%}
    </title>
    <link rel="stylesheet" href="{{url_for('static',filename='css/style.css')}}">
</head>
<body>

    <header>
        <div class="container">
            <h1>My To-Do App</h1>
            <nav>
                <a href="{{url_for('tasks.view_task')}}">Home</a>
                {% if 'user' in session%}
                    <a href="{{url_for('auth.logout')}}">Logout</a>
                {%else%}
                    <a href="{{url_for('auth.login')}}">Login</a>
                {%endif%}
            </nav>
        </div>
    </header>

    <main class="container">
        {%with messages = get_flashed_messages(with_categories = True)%}
            {% for category, message in messages %}
                <div class="flash{{category}}">{{mesaage}}</div>
            {%endfor%}
        {%endwith%}

        {% block content %} {% endblock %}
    </main>

    <footer>
        <div class="container">
            <p>First Flash App by Pritam!{{2025}}</p>
        </div>
    </footer>
</body>
</html>

app/templates/login.html
{% extends "base.html" %}
{% block title %} Login {% endblock %}

{% block content%}

<div class="login-box">
    <h2>Login</h2>
    <form method="POST">
        <div class="form-group">
            <label for="username">Username</label>
            <input for="text" name="username" id="username" required>
        </div>

        <div class="form-group">
            <label for="password">Password</label>
            <input for="password" name="password" id="password" required>
        </div>

        <button type="submit" class="btn">Login</button>
    </form>
</div>

{% endblock %}

app/templates/register.html
{% extends "base.html" %}
{% block title %} Register {% endblock %}
{% block content%}

<h2>Registration Comming Soon...</h2>

<!-- <div class=""></div> -->

{% endblock %}

app/templates/task.html
{% extends "base.html" %}
{% block title %} Tasks {% endblock %}
{% block content%}

<div class="task-box">
    <h2>Your Tasks</h2>
    <form action="{{url_for('tasks.add_task')}}" method="POST" class="task-form">
        <input type="text" name="title" placeholder="New Task" required>
        <button type="submit">Add</button>
    </form>

    {% if task %}
    <form method="POST" action="{{url_for('tasks.clear_task')}}">
        <button type="submit" class="btn btn-clear">Delete All Tasks</button>
    </form>

    <br>

    <table class="tasks-table">
        <thead>
            <tr>
                <th>Task</th>
                <th>Status</th>
                <th>Change</th>
            </tr>
        </thead>
        <tbody>
            {%for task in tasks%}
            <tr>
                <td>{{loop.index}}</td>
                <td>{{loop.title}}</td>
                <td>
                    <span class="badge {{task.status | lower}}">{{task.status}}/span>
                </td>
                <td>
                    <!-- status toggling code -->
                    <form action="{{url_for('tasks.toggle_status', task_id = task.id)}}" method="POST">
                        <button class="btn-small" type="submit">Next</button>
                    </form>
                </td>
            </tr>
            {%endfor%}
        </tbody>
    </table>
    {%else%}
    <p>No task yet. Add one above</p>
    {%endif%}
</div>

{% endblock %}